package com.bdt.framework.mapper;

import com.bdt.framework.entity.RechargeRecord;
import java.util.List;

public interface RechargeRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_record
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_record
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int insert(RechargeRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_record
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    RechargeRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_record
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    List<RechargeRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_record
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int updateByPrimaryKey(RechargeRecord record);
}