package com.bdt.framework.mapper;

import com.bdt.framework.entity.WebTaskExecuteLog;
import java.util.List;

public interface WebTaskExecuteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_execute_log
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_execute_log
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int insert(WebTaskExecuteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_execute_log
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    WebTaskExecuteLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_execute_log
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    List<WebTaskExecuteLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task_execute_log
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int updateByPrimaryKey(WebTaskExecuteLog record);
}