package com.bdt.framework.mapper;

import com.bdt.framework.entity.WebTask;
import java.util.List;

public interface WebTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int insert(WebTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    WebTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    List<WebTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table web_task
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    int updateByPrimaryKey(WebTask record);
}