package com.bdt.framework.entity;

import java.math.BigDecimal;

public class Admin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.account
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String account;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.passwd
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String passwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.balance
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private BigDecimal balance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.account
     *
     * @return the value of admin.account
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getAccount() {
        return account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.account
     *
     * @param account the value for admin.account
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setAccount(String account) {
        this.account = account;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.passwd
     *
     * @return the value of admin.passwd
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getPasswd() {
        return passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.passwd
     *
     * @param passwd the value for admin.passwd
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.balance
     *
     * @return the value of admin.balance
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.balance
     *
     * @param balance the value for admin.balance
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }
}