package com.bdt.framework.entity;

import java.math.BigDecimal;
import java.util.Date;

public class RechargeRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.order_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.order_name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String orderName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.total_fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private BigDecimal totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.order_desc
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String orderDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_record.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean success;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.id
     *
     * @return the value of recharge_record.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.id
     *
     * @param id the value for recharge_record.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.order_id
     *
     * @return the value of recharge_record.order_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.order_id
     *
     * @param orderId the value for recharge_record.order_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.order_name
     *
     * @return the value of recharge_record.order_name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getOrderName() {
        return orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.order_name
     *
     * @param orderName the value for recharge_record.order_name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setOrderName(String orderName) {
        this.orderName = orderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.total_fee
     *
     * @return the value of recharge_record.total_fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.total_fee
     *
     * @param totalFee the value for recharge_record.total_fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.order_desc
     *
     * @return the value of recharge_record.order_desc
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getOrderDesc() {
        return orderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.order_desc
     *
     * @param orderDesc the value for recharge_record.order_desc
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setOrderDesc(String orderDesc) {
        this.orderDesc = orderDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.create_time
     *
     * @return the value of recharge_record.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.create_time
     *
     * @param createTime the value for recharge_record.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.admin_id
     *
     * @return the value of recharge_record.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.admin_id
     *
     * @param adminId the value for recharge_record.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_record.success
     *
     * @return the value of recharge_record.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_record.success
     *
     * @param success the value for recharge_record.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }
}