package com.bdt.framework.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.status
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.validatecode
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String validatecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.registertime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Date registertime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.tokenexptime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Long tokenexptime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.status
     *
     * @return the value of user.status
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.status
     *
     * @param status the value for user.status
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.validatecode
     *
     * @return the value of user.validatecode
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getValidatecode() {
        return validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.validatecode
     *
     * @param validatecode the value for user.validatecode
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setValidatecode(String validatecode) {
        this.validatecode = validatecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.registertime
     *
     * @return the value of user.registertime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Date getRegistertime() {
        return registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.registertime
     *
     * @param registertime the value for user.registertime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setRegistertime(Date registertime) {
        this.registertime = registertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.tokenexptime
     *
     * @return the value of user.tokenexptime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Long getTokenexptime() {
        return tokenexptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.tokenexptime
     *
     * @param tokenexptime the value for user.tokenexptime
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setTokenexptime(Long tokenexptime) {
        this.tokenexptime = tokenexptime;
    }
}