package com.bdt.framework.entity;

import java.math.BigDecimal;
import java.util.Date;

public class WebTaskExecuteLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.web_task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer webTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.current_url
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String currentUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.ip
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private BigDecimal fee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String domain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_execute_log.exception
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String exception;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.id
     *
     * @return the value of web_task_execute_log.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.id
     *
     * @param id the value for web_task_execute_log.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.keyword
     *
     * @return the value of web_task_execute_log.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.keyword
     *
     * @param keyword the value for web_task_execute_log.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.admin_id
     *
     * @return the value of web_task_execute_log.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.admin_id
     *
     * @param adminId the value for web_task_execute_log.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.create_time
     *
     * @return the value of web_task_execute_log.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.create_time
     *
     * @param createTime the value for web_task_execute_log.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.web_task_id
     *
     * @return the value of web_task_execute_log.web_task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getWebTaskId() {
        return webTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.web_task_id
     *
     * @param webTaskId the value for web_task_execute_log.web_task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setWebTaskId(Integer webTaskId) {
        this.webTaskId = webTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.current_url
     *
     * @return the value of web_task_execute_log.current_url
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getCurrentUrl() {
        return currentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.current_url
     *
     * @param currentUrl the value for web_task_execute_log.current_url
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setCurrentUrl(String currentUrl) {
        this.currentUrl = currentUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.ip
     *
     * @return the value of web_task_execute_log.ip
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.ip
     *
     * @param ip the value for web_task_execute_log.ip
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.fee
     *
     * @return the value of web_task_execute_log.fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public BigDecimal getFee() {
        return fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.fee
     *
     * @param fee the value for web_task_execute_log.fee
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setFee(BigDecimal fee) {
        this.fee = fee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.domain
     *
     * @return the value of web_task_execute_log.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.domain
     *
     * @param domain the value for web_task_execute_log.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.success
     *
     * @return the value of web_task_execute_log.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.success
     *
     * @param success the value for web_task_execute_log.success
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setSuccess(Boolean success) {
        this.success = success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_execute_log.exception
     *
     * @return the value of web_task_execute_log.exception
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getException() {
        return exception;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_execute_log.exception
     *
     * @param exception the value for web_task_execute_log.exception
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setException(String exception) {
        this.exception = exception;
    }
}