package com.bdt.framework.entity;

public class WebTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String keyword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.disabled
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.page_title
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String pageTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.times
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer times;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String domain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.id
     *
     * @return the value of web_task.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.id
     *
     * @param id the value for web_task.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.keyword
     *
     * @return the value of web_task.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getKeyword() {
        return keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.keyword
     *
     * @param keyword the value for web_task.keyword
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setKeyword(String keyword) {
        this.keyword = keyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.admin_id
     *
     * @return the value of web_task.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.admin_id
     *
     * @param adminId the value for web_task.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.disabled
     *
     * @return the value of web_task.disabled
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.disabled
     *
     * @param disabled the value for web_task.disabled
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setDisabled(Boolean disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.page_title
     *
     * @return the value of web_task.page_title
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getPageTitle() {
        return pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.page_title
     *
     * @param pageTitle the value for web_task.page_title
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setPageTitle(String pageTitle) {
        this.pageTitle = pageTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.times
     *
     * @return the value of web_task.times
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getTimes() {
        return times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.times
     *
     * @param times the value for web_task.times
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setTimes(Integer times) {
        this.times = times;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task.domain
     *
     * @return the value of web_task.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task.domain
     *
     * @param domain the value for web_task.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }
}