package com.bdt.framework.entity;

import java.util.Date;

public class WebTaskItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.finished
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean finished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.hour
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Integer hour;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.running
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private Boolean running;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column web_task_item.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    private String domain;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.id
     *
     * @return the value of web_task_item.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.id
     *
     * @param id the value for web_task_item.id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.task_id
     *
     * @return the value of web_task_item.task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.task_id
     *
     * @param taskId the value for web_task_item.task_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.admin_id
     *
     * @return the value of web_task_item.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.admin_id
     *
     * @param adminId the value for web_task_item.admin_id
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.finished
     *
     * @return the value of web_task_item.finished
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getFinished() {
        return finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.finished
     *
     * @param finished the value for web_task_item.finished
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setFinished(Boolean finished) {
        this.finished = finished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.hour
     *
     * @return the value of web_task_item.hour
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Integer getHour() {
        return hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.hour
     *
     * @param hour the value for web_task_item.hour
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setHour(Integer hour) {
        this.hour = hour;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.create_time
     *
     * @return the value of web_task_item.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.create_time
     *
     * @param createTime the value for web_task_item.create_time
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.running
     *
     * @return the value of web_task_item.running
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public Boolean getRunning() {
        return running;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.running
     *
     * @param running the value for web_task_item.running
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setRunning(Boolean running) {
        this.running = running;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column web_task_item.domain
     *
     * @return the value of web_task_item.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column web_task_item.domain
     *
     * @param domain the value for web_task_item.domain
     *
     * @mbggenerated Fri Sep 30 13:56:21 CST 2016
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }
}